language: rust
rust: nightly
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  - DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
  - CODENAME=$(lsb_release -cs)
  - echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
  - sudo apt-get update
  - sudo apt-get install mesos protobuf-compiler
