[package]
name = "mesos"
version = "0.0.1"
authors = ["Connor Doyle <connor@mesosphere.io>", "Nandor Kracser <bonifaido@gmail.com>"]

[dependencies]
hyper = "0.5.2"
env_logger = "0.3.1"
protobuf = "1.0.0"

[dependencies.proto]
path = "proto"