[package]
name = "mesos"
version = "0.0.1"
authors = ["Connor Doyle <connor@mesosphere.io>",
           "Nandor Kracser <bonifaido@gmail.com>"]

[dependencies]
hyper = "0.5"
log = "0.3"
protobuf = "1.0"

[dependencies.proto]
path = "proto"

[dependencies.zookeeper]
path = "../rust-zookeeper"

[dev-dependencies]
env_logger = "0.3"
